### ISSUE TITLE
An immutable diagram that I can then make copies of and edit

### ISSUE THREAD

**Issue by stephen-ciq** [PrecursorApp/precursor#181]
Perhaps there is currently a way to achieve this, but I don't know how.

I want an immutable precursor diagram that I can then make copies of and edit in precursor.  I want this because I see this as essential to the conceptual purity of storing them in github, since a commit is not changeable (well, it is, if you force it to be, but commits aren't really _meant_ to be changeable, and I don't amend my commits that I've pushed anywhere).
I can't see a way to do that right now, because i can't import a diagram from any format so far as I can tell, and I also can't find a way to make a document permanently uneditable by anyone.

**Comment by dwwoelfel** [comment]
The easiest way to accomplish this would be through hitting Cmd+a (or Ctrl+a on a PC) to select everything in the document, then hit Cmd+c (Ctrl+c on PC) to copy it. Precursor will put an svg into your clipboard that matches the document on the page, but also includes metadata that allows Precursor to replicate the document when you paste it back. 

If I do the process with [this doc](https://precursorapp.com/document/Untitled-17592208964712), I get https://gist.github.com/dwwoelfel/c191df8a51c94892c9438843f41593ff. If you look at the [raw version of the gist](https://gist.githubusercontent.com/dwwoelfel/c191df8a51c94892c9438843f41593ff/raw/5ab3b9c6a61a3cdf2f810e03f4806e5cc25dedb3/precursor-doc.svg), you can see the metadata. Then you can take that and paste it into a new doc.

But there's an even easier way! If you click the Hamburger menu at the top left and click "Clipboard History", you'll see every single thing you've ever copied out of a Precursor doc. Copy your template and you'll see it there. Click the star icon to save it. Click on the preview to paste it into your doc.

> I also can't find a way to make a document permanently uneditable by anyone.
You can make a document read-only, so that you're the only one allowed to edit it. To do that, click the Hamburger menu at the top-left, click "Sharing", then hover over "Public" at the bottom.

**Comment by stephen-ciq** [comment]
> If you look at the raw version of the gist, you can see the metadata. Then you can take that and paste it into a new doc.
That's what I needed (since I need to share it with team members); thanks!

> Click the star icon to save it.
Does the star icon save it, or just "favorite" it so it is listed at the top?

**Comment by dwwoelfel** [comment]
> Does the star icon save it, or just "favorite" it so it is listed at the top?

You're right, it just favorites it so that it sticks to the top. I updated the comment so that people in the future aren't confused.
